### PR TITLE
Fixed Catalyst configuration check failing when `integrate_targets` is false

### LINKED ISSUE #39: Failed with `PodBuilder::Command::Build#should_build_catalyst` when `integrate_targets: false`.
image

ref: https://github.com/CocoaPods/CocoaPods/blob/123f2d02f42075fa9f3b1bc729b342bd844efb44/lib/cocoapods/installer/analyzer.rb#L511

### PR DESCRIPTION
**Pull request by knchst**
Fixed #39

### CODE REVIEW

File: lib/pod_builder/command/build.rb [hunk 1]
```diff
@@ -154,7 +154,38 @@ def self.call
...
+                            # Find root `xcodeproj`
+                            project = Xcodeproj::Project.open(PodBuilder.find_xcodeproj)
+                            root_project_build_setting = project
+                                                          .root_object
+                                                          .targets
+                                                          .map { |u| u.build_configuration_list.build_configurations.map { |v| v.build_settings } }
+                                                          .flatten
+
+                            user_projects_build_settings | root_project_build_setting
+                         end
```
Comment (tcamin) [inline lib/pod_builder/command/build.rb:187]:
```suggestion
        if integrate_targets
            build_settings =installer.analysis_result.targets.map { |t| t.user_project.root_object.targets.map { |u| u.build_configuration_list.build_configurations.map { |v| v.build_settings } } }.flatten
        else
            # Find all `xcodeproj` in Podfile
            user_projects_build_settings = installer.analysis_result.targets.map { |t|
                user_project_path = PodBuilder.basepath + '/' + t.target_definition.user_project_path
                project = Xcodeproj::Project.open(user_project_path)
                project.root_object.targets.map { |u| u.build_configuration_list.build_configurations.map { |v| v.build_settings } }
            }
            .flatten
            .compact

            # Find root `xcodeproj`
            project = Xcodeproj::Project.open(PodBuilder.find_xcodeproj)
            root_project_build_setting = project
                                            .root_object
                                            .targets
                                            .map { |u| u.build_configuration_list.build_configurations.map { |v| v.build_settings } }
                                            .flatten

            build_settings = user_projects_build_settings | root_project_build_setting
        end                        
```

Comment (knchst) [reply lib/pod_builder/command/build.rb]: @tcamin Fixed at 3c726b1

**Review by tcamin — APPROVED** [review]

**Comment by tcamin** [comment]
Thanks!
